As a user I should be able to maintain boards Test 93
stoyanov-ivelin/kanban-board pull request #10
Opened 2021-09-16 15:29 UTC by stoyanov-ivelin

Add boards config page that lets a user add new boards and manage existing ones.

A board's columns can now be renamed, deleted, statuses can be added and removed from them and their position can now be changed.

Users can also select which board to see in the main boards page.

2021-09-17 08:19 UTC, MilenIvanovv commented on src/components/BoardsConfig/BoardsTabs/BoardsTabs.tsx
> +export default function BoardsTabs() {
Is this used anywhere?

2021-09-17 08:44 UTC, MilenIvanovv requested changes
I think the code looks great. I have some comments and suggestions about the user experience.

1. Now if you want to drag status from column In Progress to Done, you have to drag the status to unused status and the Done column. It will be more easier for the user if it can be done with one move.
2. What happens if they are two boards with the same name?
3. When I create 20 columns I cannot drag status or issues to the last ones.
4. I have a suggestion for the boards view. Columns can be always horizontal and their width can depend on the number of columns created. If there are > 4 or 5 columns there can be a horizontal scroll.
5. On boards config I think a new visitor would not know what is the empty rectangle for. A labal can be added

2021-09-17 08:44 UTC, MilenIvanovv commented on src/components/BoardsConfig/BoardsTabs/BoardsTabs.tsx
> +export default function BoardsTabs() {
Is this used anywhere?

2021-09-17 08:51 UTC, stoyanov-ivelin commented on src/components/BoardsConfig/BoardsTabs/BoardsTabs.tsx
> +export default function BoardsTabs() {
done

2021-09-20 12:38 UTC, MilenIvanovv approved these changes
LGTM, the small issue is found is that in boards config the horizontal scroll is not visible

2021-09-20 13:41 UTC, merged